language: php

os: linux
dist: trusty
sudo: required

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

addons:
  firefox: latest

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  # Install composer dependencies
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

  # Download selenium standalone server and the geckodriver
  - travis_retry wget http://goo.gl/EUxR76 -O /tmp/selenium.jar
  - travis_retry wget https://goo.gl/k3M4M1 -O /tmp/geckodriver.tar.gz
  - tar -xzvf /tmp/geckodriver.tar.gz --directory /tmp

before_script:
  # Start X virtual framebuffer
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

  # Run Selenium standalone server, silently...
  - >
    sudo java
    -Dwebdriver.gecko.driver=/tmp/geckodriver
    -Dwebdriver.firefox.bin=`which firefox`
    -jar /tmp/selenium.jar &> /dev/null &
  - sleep 3

script:
  # Don't generate coverage for functional tests, as they may give a false sense of security...
  - vendor/bin/phpunit --testsuite unit --coverage-clover tests/coverage/clover.xml
  - vendor/bin/phpunit --testsuite functional

after_script:
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then vendor/bin/codacycoverage clover tests/coverage/clover.xml; fi;
